### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Hyejilee123** [Jeongmyung-KANG/JEWEL_Constituents_Method#1]
![helpme](https://github.com/Jeongmyung-KANG/JEWEL_Constituents_Method/assets/144301334/0b738dce-538c-4f07-b2f2-2a31e4587a92)

**Comment by Hyejilee123** [comment]
oh yeah

**Comment by Jeongmyung-KANG** [comment]
If you prepared anything, push it. 
ASAP

**Comment by Jeongmyung-KANG** [comment]
혜지씨 정리좀 해주세요 .root는 데이터에, plot은 figure에
